# -*- coding: utf-8 -*-
"""Data_selected.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKsvX6BP5cI_bgzOXaxJJEpv4S0W0paV
"""

data_set = 'circa-data.tsv'

import pandas as pd

def count_goldstandard2_labels(file_path):

    df = pd.read_csv(file_path, sep='\t')


    label_counts = df['goldstandard2'].value_counts()


    print("Goldstandard2 Label Counts:")
    print(label_counts)

    return label_counts


count_goldstandard2_labels('circa-data.tsv')

def filter_and_save_samples(file_path, yes_output, no_output):

    df = pd.read_csv(file_path, sep='\t')

    yes_samples = df[df['goldstandard2'] == 'Yes'].sample(n=500, random_state=42)
    no_samples = df[df['goldstandard2'] == 'No'].sample(n=500, random_state=42)

    yes_samples.to_csv(yes_output, sep='\t', index=False)
    no_samples.to_csv(no_output, sep='\t', index=False)

    print(f"Filtered Yes samples saved to {yes_output}")
    print(f"Filtered No samples saved to {no_output}")
filter_and_save_samples('circa-data.tsv', 'yes_samples.tsv', 'no_samples.tsv')

def filter_and_save_samples(file_path, yes_output, no_output):

    df = pd.read_csv(file_path, sep='\t')


    yes_samples = df[df['goldstandard2'] == 'Yes'][['question-X', 'answer-Y']].sample(n=500, random_state=42)
    no_samples = df[df['goldstandard2'] == 'No'][['question-X', 'answer-Y']].sample(n=500, random_state=42)


    yes_samples.to_csv(yes_output, sep='\t', index=False)
    no_samples.to_csv(no_output, sep='\t', index=False)

    print(f"Filtered Yes samples saved to {yes_output}")
    print(f"Filtered No samples saved to {no_output}")

filter_and_save_samples('circa-data.tsv', 'yes_QA.tsv', 'no_QA.tsv')